### ISSUE TITLE
issue with new access token when the token is expired

### ISSUE THREAD

**Issue by arokia-innominds** [procore/ruby-sdk#36]
I am using the following method to get new token but i am getting the error.
token = Procore::Auth::AccessTokenCredentials.new(client_id: ENV.fetch("PROCORE_CLIENT_ID"), client_secret: ENV.fetch("PROCORE_CLIENT_SECRET"), host: ENV["PROCORE_BASE_API_PATH"])

newToken = token.refresh({token: config.accessToken, refresh: config.refreshToken})

but i am receiving the following error
Procore::OAuthError: The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.

Please help me to resolve this

**Comment by PatKoperwas** [comment]
Please look at the full example: https://github.com/procore/ruby-sdk#full-example
Or at the sample app: https://github.com/procore/Procore-Sample-ROR

You will first need to have a user sign in using OAuth, then in the callback run the provided code to store the token. 

Documentation Links:
https://developers.procore.com/documentation/making-first-call
https://developers.procore.com/documentation/oauth-introduction


Useful Gems:
https://github.com/omniauth/omniauth-oauth2
https://github.com/procore/omniauth-procore
