### ISSUE TITLE
Resource not found error when fetching projects 

### ISSUE THREAD

**Issue by adsherpa** [procore/ruby-sdk#40]
Hi, I am facing 404 error when fetching project list for a given company.
This is for our customer who really needs this working.

```ruby 
GET https://api.procore.com/rest/v1.0/projects?company_id=<company_id>
```
SDK call:
```ruby
client.get("projects", query:{company_id:<company_id>}
```

Response:
```ruby
Procore::NotFoundError
404
The URI requested is invalid or the resource requested does not exist.

#<Procore::Response:0x00007f3e3c0e63a8>
```
I am using latest sdk for ruby version 1.1.0
Same call works when using postman.

**Comment by nick-morrill** [comment]
Hi @adsherpa -- you may want to reach out to Procore's API Support team (apisupport@procore.com) if you need more urgent assistance.

I believe you'll want to specify a company_id value in an 'options' parameter hash in your request, something like:

`client.get("projects", query:{company_id:<company_id>}, options: {company_id: <company_id>})`

**Comment by adsherpa** [comment]
Hi @nick-morrill thank you, yes I have figured that out now. And also am in touch with apisupport as well.
thank you very much.
